### PR TITLE
Add haj email template

### PR DESCRIPTION
**Pull request by adriansalamon**
I want to be able to send emails from Haj via spam :)

### CODE REVIEW

**Review by Herkarl — APPROVED** [review]
Interesting! I see that there already seems to have been support for selecting a different template! 

Lgtm, seems like it should work. I assume it worked locally?

Reasonable since we own metaspexet.se. Would there be some other setup we have to do to be able to send mails from it here?

**Comment by Herkarl** [comment]
What do you think @mathiasmagnusson?

**Comment by adriansalamon** [comment]
@Herkarl I think we might need to add metaspexet.se as a verified domain in AWS SES, but it was a while ago I last used it.

**Review by foodelevator — APPROVED** [review]
Looks good and seems reasonable!

Yes, we (probably meaning I) will have to configure the domain to be able to send emails from it.

I think we can merge this before that so that metaspexet can at least test the template right away

**Comment by Herkarl** [comment]
Deployed now

**Comment by foodelevator** [comment]
`metaspexet.se` has now been added to AWS SES!

**Pull request merged**
